services:
    api:
        build:
            context: .
            dockerfile: Presentation/Dockerfile
        image: books-presentation
        ports:
            - "8080:8080"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:8080
        networks:
          - default