# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - WebAppTest3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: test3registry-bgb8b3edc2dyegbw.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_2E8984E5D13342B5A37EB6C9D9C1B6EC }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_C780838287FA4905A7F3C2EED90A23A7 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: test3registry-bgb8b3edc2dyegbw.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_2E8984E5D13342B5A37EB6C9D9C1B6EC }}/nginx:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8ECD38A3C1DA4EA2A9149BEDDFBC2E9A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_64D1BB7B124B4C76A13EECC3992FCF26 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7D13982704F246F68F62A35180913052 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'WebAppTest3'
          slot-name: 'Production'
          images: 'test3registry-bgb8b3edc2dyegbw.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_2E8984E5D13342B5A37EB6C9D9C1B6EC }}/nginx:${{ github.sha }}'
          